### ISSUE TITLE
Spacing issue on sub categories, sections are not aligned

### ISSUE THREAD

**Issue by tmarsdn** [DFE-Digital/npd-find-and-explore#344] opened 2019-09-10 09:23 UTC
**Tested on staging**: https://s112p01-find-npd-data-s112p01-staging.azurewebsites.net/categories
**Browser**: Chrome
**OS**: Windows 10

**Steps to reproduce**
------------------------
1. Navigate to Home > Attainment
2. Notice that the Sub-Categories are not aligned correctly on the page and the 'Number of qualifications achieved' has more white space underneath compare to the opposing sections

Please see attached image.

![Spacing of sub categories](https://user-images.githubusercontent.com/53817849/64601452-de613f80-d3b4-11e9-97ab-0c1c68b94c7e.png)

**Comment by DFEchristian** [comment] 2019-09-10 14:21
Discussed with Rich and happy for this to be addressed post launch.

**Comment by DFEchristian** [comment] 2019-09-10 15:11
This is a duplicate of [#212](https://github.com/DFE-Digital/npd-find-and-explore/issues/212) so should be read before trying to fix this.

**Comment by petelonsdale** [comment] 2019-10-11 10:29
I'd suggest temporarily increasing the min-height on these to stop items not wrapping correctly. We should also list items alphabetically.

![image](https://user-images.githubusercontent.com/5918321/66645054-5d4ad180-ec1a-11e9-8617-376d0907f841.png)

**Closed as completed** 2020-07-09 10:32 UTC
Labels: Bug
